name = "TableMetadataTools"
uuid = "9ce81f87-eacc-4366-bf80-b621a3098ee2"
authors = ["Bogumił Kamiński <bkamins@sgh.waw.pl>"]
version = "0.1.0"

[deps]
DataAPI = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
DataAPI = "1.12.0"
Tables = "1.9.0"
julia = "1.6"
